github:
  link_to_your_github

stackoverflow:
  link_to_your_stackoverflow

linkedin:
  link_to_your_linkedin

email:
  your_mail

resume:
  link_to_your_resume

profile_picture:
  link_to_your_profile_picture
